/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urna.org.com;

import central.org.com.Candidatos;
import central.org.com.Eleitor;
import central.org.com.VisaoCadastraC;
import static central.org.com.VisaoCadastraC.candidatos;
import central.org.com.VisaoCadastraP;
import central.org.com.VisaoEleitor;
import central.org.com.VisaoMenu;
import static central.org.com.VisaoMenu.c;
import static central.org.com.VisaoMenu.eleitor;
import com.google.gson.Gson;
import java.awt.BorderLayout;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author hera
 */
public class UrnaVisao extends javax.swing.JPanel {
public static Voto voto[] = new Voto[50];
int i;

    /**
     * Creates new form UrnaVisao
     */
    public UrnaVisao() {
       
        
        
        initComponents();
        
        cbxCandidato.setSelectedItem(null);
        cbxCandidato.removeAllItems();
        cbxPartido.setSelectedItem(null);
        cbxPartido.removeAllItems();
        
        for(i = 0; i < VisaoMenu.c.size();i++){
            cbxCandidato.addItem(VisaoMenu.c.get(i).getNome());
        }
        
        for(i = 0; i < VisaoMenu.p.size(); i++){  
           cbxPartido.addItem(VisaoMenu.p.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCandidato = new javax.swing.JComboBox<>();
        txtCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEleitor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNCandidato = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUrna = new javax.swing.JTextField();
        bttFoto = new javax.swing.JButton();
        cbxPartido = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        bttVotar = new javax.swing.JButton();
        bttBranco = new javax.swing.JButton();
        bttNulo = new javax.swing.JButton();
        bttCancela = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jPanel1.setName("txtDate"); // NOI18N

        jLabel1.setText("URNA ELETRONICA");

        jLabel2.setText("CPF");

        jLabel3.setText("Candidato");

        cbxCandidato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCandidato.setName(""); // NOI18N
        cbxCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCandidatoActionPerformed(evt);
            }
        });

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        jLabel4.setText("Título de Eleitor");

        jLabel5.setText("Nº Candidato");

        txtNCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCandidatoActionPerformed(evt);
            }
        });

        jLabel6.setText("Partido");

        jLabel7.setText("Nome");

        jLabel8.setText("Nº Urna");

        bttFoto.setText("Buscar Imagem");

        cbxPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrna))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNCandidato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttFoto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bttFoto)
                    .addComponent(cbxPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        bttVotar.setText("Votar");
        bttVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVotarActionPerformed(evt);
            }
        });

        bttBranco.setText("Branco");
        bttBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBrancoActionPerformed(evt);
            }
        });

        bttNulo.setText("Nulo");
        bttNulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bttVotar)
                .addGap(84, 84, 84)
                .addComponent(bttBranco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(bttNulo)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVotar)
                    .addComponent(bttBranco)
                    .addComponent(bttNulo))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        bttCancela.setText("Cancela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(706, 706, 706)
                        .addComponent(bttCancela)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(bttCancela)))
                .addGap(428, 428, 428))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVotarActionPerformed
       Date a = new Date();
       a.getTime();
       String nome = txtNome.getText();
       String cpf = txtCPF.getText();
       int numeroUrna = Integer.parseInt(txtUrna.getText());
       String candidato = (String) cbxCandidato.getSelectedItem();
       int titulo = Integer.parseInt(txtEleitor.getText());
       int nCandidato = Integer.parseInt(txtNCandidato.getText());
       String partido = (String) cbxPartido.getSelectedItem();
       
       int n;
       int existeE = 0;
       
        System.out.println("OK");
       for(n = 0; n < eleitor.size();n++){
           if((eleitor.get(n).getCpf().equals(cpf) && (eleitor.get(n).getTituloEleitor()==titulo))){
              System.out.println("OK");
               existeE++;
           }
       }
      
       int existeC = 0;
       for(n = 0; n < VisaoMenu.c.size();n++){
           if((c.get(n).getNome().equals(candidato))&&(c.get(n).getPartidoNumero()==nCandidato)){
               existeC++;
               System.out.println("OK");
           }
       }
       
       for(n = 0; voto[n] !=null;n++){
           
       }
        System.out.println("passou");
       if((n<=50)&&(existeE > 0)&&(existeC > 0)){
           Voto vote = new Voto(nome,numeroUrna,titulo,candidato,nCandidato,partido);
           voto[n] = vote;
            showMessageDialog(null,"Voto efetuado");
       }
          
          
            Gson gson = new Gson();
           String json = gson.toJson(voto);
           try {
                FileWriter writer = new FileWriter("voto.json");
                writer.write(json);
                writer.close();
                
           } catch (IOException ex) {
                Logger.getLogger(UrnaVisao.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           
       
       
       
       
       
        
    }//GEN-LAST:event_bttVotarActionPerformed

    private void cbxCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCandidatoActionPerformed
        
    }//GEN-LAST:event_cbxCandidatoActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtNCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNCandidatoActionPerformed

    private void bttBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBrancoActionPerformed
       showMessageDialog(null,"Voto efetuado");
    }//GEN-LAST:event_bttBrancoActionPerformed

    private void bttNuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNuloActionPerformed
       showMessageDialog(null,"Voto efetuado");
    }//GEN-LAST:event_bttNuloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBranco;
    private javax.swing.JButton bttCancela;
    private javax.swing.JButton bttFoto;
    private javax.swing.JButton bttNulo;
    private javax.swing.JButton bttVotar;
    private javax.swing.JComboBox<String> cbxCandidato;
    private javax.swing.JComboBox<String> cbxPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEleitor;
    private javax.swing.JTextField txtNCandidato;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUrna;
    // End of variables declaration//GEN-END:variables
}
