/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package central.org.com;

import com.google.gson.Gson;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import org.json.JSONException;
import urna.org.com.Urna;
import static urna.org.com.Urna.candidato;
import urna.org.com.UrnaVisao;

import org.json.JSONArray;
import org.json.JSONObject;
import static urna.org.com.UrnaVisao.voto;
import urna.org.com.Voto;

/**
 *
 * @author hera
 */
public class VisaoMenu extends javax.swing.JFrame {
Urna urna = new Urna();
public static ArrayList<PartidoPolitico> p ; 
public static ArrayList<Candidatos> c ;
public static ArrayList<Eleitor> eleitor;
public static ArrayList<Voto> vote;

    /**
     * Creates new form VisaoMenu
     */
    public VisaoMenu() {
        
        initComponents();
        c = new ArrayList(); 
        p = new ArrayList();
        eleitor = new ArrayList(); 
        vote = new ArrayList();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bbtEleitor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bttVotar = new javax.swing.JButton();
        bttCadastrarUrna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bbtEleitor.setText("Cadastro Eleitor");
        bbtEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtEleitorActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastro Candidato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastro Partido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Enviar Relação de Candidatos ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Enviar Relação de Eleitores");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Buscar Votos da Urna");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Mostrar Resulltado Eleição");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Módulo Central:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addGap(44, 44, 44)
                .addComponent(jButton5)
                .addGap(41, 41, 41)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bbtEleitor)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3)
                        .addGap(34, 34, 34)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(bbtEleitor)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(38, 38, 38))
        );

        jLabel2.setText("Módulo Urna:");

        bttVotar.setText("Votar");
        bttVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVotarActionPerformed(evt);
            }
        });

        bttCadastrarUrna.setText("Cadastrar Urnas");
        bttCadastrarUrna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarUrnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bttVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttCadastrarUrna, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVotar)
                    .addComponent(bttCadastrarUrna))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         VisaoCadastraC visao3 = new VisaoCadastraC();
        visao3.setVisible(true);
         
        JFrame a3 = new JFrame();
        a3.add(visao3);
       
       JFrame f3 = new JFrame();
       f3.setLayout(new BorderLayout());
       f3.add(visao3, BorderLayout.CENTER);
       
    f3.pack();
    
    f3.setVisible(true);
     a3.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VisaoCadastraP tela4 = new VisaoCadastraP();
         tela4.setVisible(true);
         JFrame frame4 = new JFrame();
         frame4.add(tela4);
         JFrame f4 = new JFrame();
         f4.setLayout(new BorderLayout());
         f4.add(tela4, BorderLayout.CENTER);
         f4.pack();
         f4.setVisible(true);
         frame4.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bttVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVotarActionPerformed
        UrnaVisao tela5 = new UrnaVisao();
         tela5.setVisible(true);
         JFrame frame5 = new JFrame();
         frame5.add(tela5);
         JFrame f5 = new JFrame();
         f5.setLayout(new BorderLayout());
         f5.add(tela5, BorderLayout.CENTER);
         f5.pack();
         f5.setVisible(true);
         frame5.dispose();
    }//GEN-LAST:event_bttVotarActionPerformed

    private void bttCadastrarUrnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarUrnaActionPerformed
        int i;
        for(i = 0;urna.candidato[i]!=null;i++ ){
        }
        if(i <=50){
         urna.adicionaCandidato(VisaoCadastraC.candidatos[i]);
        }
        for(i = 0;urna.eleitor[i]!=null;i++ ){
            
        }
        if(i <= 50){
            urna.adicionaEleitor(VisaoEleitor.eleitor[i]);
        }
        urna.setNumero();
    }//GEN-LAST:event_bttCadastrarUrnaActionPerformed

    private void bbtEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtEleitorActionPerformed
        VisaoEleitor tela2 = new VisaoEleitor();
         tela2.setVisible(true);
         JFrame frame1 = new JFrame();
         frame1.add(tela2);
         JFrame f1 = new JFrame();
         f1.setLayout(new BorderLayout());
         f1.add(tela2, BorderLayout.CENTER);
         f1.pack();
         f1.setVisible(true);
         frame1.dispose();
    }//GEN-LAST:event_bbtEleitorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        String jsonToStr="";
        try {
            FileReader arq = new FileReader("partidos.json");
            BufferedReader lerArq = new BufferedReader(arq);
 
            String linha = lerArq.readLine(); // lê a primeira linha
            while (linha != null) {
               jsonToStr += linha;
               
               linha = lerArq.readLine(); // lê da segunda até a última linha
            }
 
            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
            e.getMessage());
        }
        
       
        try{
            int numero;
            String nome;
            JSONArray jsonarray = new JSONArray(jsonToStr);
            
            for (int i = 0; i < jsonarray.length(); i++) {
                JSONObject jsonobject = jsonarray.getJSONObject(i);
                nome    = jsonobject.getString("nome");
                numero  =  jsonobject.getInt("numero");
                PartidoPolitico partido = new PartidoPolitico(numero,nome);
                p.add(partido);
                //String name = jsonobject.getString("name");
                //String url = jsonobject.getString("url");
            }   
            
        }catch(JSONException e){
            System.out.printf("");
            //return 0;
        }
        
       
        showMessageDialog(null,"OK");                                 
        
        
       String jsonToStr1="";
        try {
            FileReader arq = new FileReader("candidatos.json");
            BufferedReader lerArq = new BufferedReader(arq);
 
            String linha1 = lerArq.readLine(); // lê a primeira linha
            
            // a variável "linha" recebe o valor "null" quando o processo
            // de repetição atingir o final do arquivo texto
            while (linha1 != null) {
               jsonToStr1 += linha1;
               
               linha1 = lerArq.readLine(); // lê da segunda até a última linha
            }
 
            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
            e.getMessage());
        }
        int j;
        
        try{
            JSONArray jsonarray = new JSONArray(jsonToStr1);
            
            for (int i = 0; i < jsonarray.length(); i++) {
                
                JSONObject jsonobject = jsonarray.getJSONObject(i);
           
                String nome    = jsonobject.getString("nome");
                String nome_partido = jsonobject.getString("nomeP");
                int numero  =  jsonobject.getInt("numeroP");
                String cpf     = jsonobject.getString("cpf");
                
                for(j = 0; j<=p.size();j++){
                    if(p.get(j).getNumero()==numero){
                        Candidatos can = new Candidatos(nome,nome_partido,numero,cpf);
                        c.add(can);
                        break;
                    }
                }
                showMessageDialog(null,"Candidato salvo com sucesso!");
                
                //String name = jsonobject.getString("name");
                //String url = jsonobject.getString("url");
            }    
        }catch(JSONException e){
            System.out.printf("");
            //return 0;
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        String jsonToStr="";
        try {
            FileReader arq = new FileReader("eleitores.json");
            BufferedReader lerArq = new BufferedReader(arq);
 
            String linha = lerArq.readLine(); // lê a primeira linha
            
            // a variável "linha" recebe o valor "null" quando o processo
            // de repetição atingir o final do arquivo texto
            while (linha != null) {
               jsonToStr += linha;
               
               linha = lerArq.readLine(); // lê da segunda até a última linha
            }
 
            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
            e.getMessage());
        }
        
       
        try{
            int numero;
            String nome;
            JSONArray jsonarray = new JSONArray(jsonToStr);
            
            for (int i = 0; i < jsonarray.length(); i++) {
                JSONObject jsonobject = jsonarray.getJSONObject(i);
                int titulo = jsonobject.getInt("tituloEleitor");
                String cpf = jsonobject.getString("cpf");
                int imagem = jsonobject.getInt("image");
                int secao  = jsonobject.getInt("seçao");
                nome  =  jsonobject.getString("nomeCompleto");
                Eleitor novo = new Eleitor(titulo,cpf,imagem,secao,nome);
                eleitor.add(novo);
                
            }   
            
        }catch(JSONException e){
            System.out.printf("");
            //return 0;
        }
       
        
        showMessageDialog(null,"Cadastrado com sucesso");   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         String jsonToStr="";
        try {
            FileReader arq = new FileReader("voto.json");
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = lerArq.readLine(); 
            while (linha != null) {
               jsonToStr += linha;
               
               linha = lerArq.readLine(); // lê da segunda até a última linha
            }
 
            arq.close();
        } catch (IOException e) {
            System.err.printf("Erro na abertura do arquivo: %s.\n",
            e.getMessage());
        }
        try{
            int numero;
            String nome;
            JSONArray jsonarray = new JSONArray(jsonToStr);
            
            for (int i = 0; i < jsonarray.length(); i++) {
                JSONObject jsonobject = jsonarray.getJSONObject(i);
                String nomeE = jsonobject.getString("nomeEleitor");
                int secao = jsonobject.getInt("secao");
                int tituloE = jsonobject.getInt("tituloE");
                String nomeCandidato = jsonobject.getString("nomeCandidato");
                int numeroC = jsonobject.getInt("numeroCandidato");
                String nomePartido = jsonobject.getString("nomePartido");
                String data = jsonobject.getString("data");
                Voto novo = new Voto(nomeE,secao,tituloE,nomeCandidato,numeroC,nomePartido);
                vote.add(novo);
                vote.get(i).setData(data);
                
            }   
            
        }catch(JSONException e){
            System.out.printf("");
            //return 0;
        }
       showMessageDialog(null,"Cadastrado com sucesso");   
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
        
        
       int ganhador = 0;
       int pos=0;
       int i,j;
       i=0;
       
       while(i < c.size()){
           for(j = 0; j < vote.size(); j++){
               
               if(c.get(i).getNome().equals(vote.get(j).getNomeCandidato())){
                   c.get(i).voto++;
                  
               }
           }
           i++;
          
       
       }
       for(i = 0; i< c.size(); i++){
           if (c.get(i).voto > ganhador){
               pos=i;
               ganhador = c.get(i).voto;
           }
       }
       
        showMessageDialog(null,"O ganhador da eleição é:"+c.get(pos).getNome()+" Total de votos:"+ganhador);   
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbtEleitor;
    private javax.swing.JButton bttCadastrarUrna;
    private javax.swing.JButton bttVotar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
